## Broadcasting example

- Example of how to loop without a for/while loop

In [2]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## Python Numpy vectors

In [9]:
a = np.random.randn(5)
print(a)

[ 0.15310053 -1.0605489  -0.15069907 -1.1214647   0.54619405]


In [10]:
print(a.shape)

(5,)


In [11]:
print(a.T)

[ 0.15310053 -1.0605489  -0.15069907 -1.1214647   0.54619405]


In [12]:
print(np.dot(a,a.T))

2.726924961381073


In [16]:
a = np.random.randn(8,1)
print(a)

[[ 1.51673968]
 [ 0.69062141]
 [ 0.78033035]
 [ 0.0072769 ]
 [ 0.02703985]
 [ 0.34899602]
 [-0.0885941 ]
 [ 0.25382917]]


In [14]:
print(a.T)

[[ 0.45747674 -0.89431977  0.79552422  1.60973576 -0.30155272]]


In [15]:
print(np.dot(a,a.T))

[[ 0.20928497 -0.40913049  0.36393382  0.73641667 -0.13795336]
 [-0.40913049  0.79980786 -0.71145304 -1.43961852  0.26968456]
 [ 0.36393382 -0.71145304  0.63285878  1.28058379 -0.23989249]
 [ 0.73641667 -1.43961852  1.28058379  2.59124923 -0.4854202 ]
 [-0.13795336  0.26968456 -0.23989249 -0.4854202   0.09093404]]


In [22]:
a=np.random.randn(4,3) # a.shape = (2, 3)a.shape=(2,3)
b=np.random.randn(3,2) #  b.shape = (2, 1)b.shape=(2,1)

c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [21]:
print(c)

[[ 1.48799092  0.30494472  0.53657284]
 [-0.55512349 -0.11919724 -3.29423991]]


In [23]:
a=np.random.randn(12288,150) 
b=np.random.randn(150,45)
c = np.dot(a,b)

In [25]:
print(c.shape)

(12288, 45)


In [26]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)

c = a*b

In [27]:
print(c)

[[-0.05294022 -0.16943814  0.58960008]
 [ 0.00965345 -0.00615123 -0.02428642]
 [ 0.5014307   0.67365387 -0.08966658]]
